
ARG BASE="debian:stable"

FROM "${BASE}" AS common

ARG PACKAGES=""

ENV GENERIC_PKG_RUNTIME="ca-certificates dumb-init ${PACKAGES}"

RUN sed -i -e 's/ main/ main contrib non-free/g' /etc/apt/sources.list \
 && apt update \
 && DEBIAN_FRONTEND=noninteractive apt install --yes --no-install-recommends ${GENERIC_PKG_RUNTIME} \
 && apt clean && rm -rf /var/lib/apt/lists/* \
 && adduser --system --group sim
