FROM alpine:latest

ENV SIMH_GIT_REPOSITORY "https://github.com/retroprom/simh.git"
ENV SIMH_GIT_REVISION "retroprom/master"

ENV SIMH_PKG_BUILD   "gcc g++ git cmake ninja libpcap-dev ncurses-dev pcre-dev vde2-dev"
ENV SIMH_PKG_RUNTIME "dumb-init libpcap ncurses pcre vde2"

ENV SIMH_CONFIG_BUILD "-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local"
ENV SIMH_CONFIG_FEATURES "-DCOMPILER_USE_LTO=YES -DENABLE_ASYNC=YES -DENABLE_GRAPHICS=NO -DENABLE_NETWORK=YES"

RUN apk add --update --virtual simh-runtime ${SIMH_PKG_RUNTIME}

RUN addgroup -S simh && adduser -S simh -G simh

WORKDIR /build/simh
COPY scripts/build-alpine-simh.sh .

