
ARG BASE="debian:stable"

FROM "${BASE}" AS common

ARG SIMPLE_PKG=""

ENV SIMPLE_PKG_RUNTIME="ca-certificates dumb-init ${SIMPLE_PKG}"

RUN apt update \
 && apt install --yes --no-install-recommends ${SIMPLE_PKG_RUNTIME} \
 && apt clean \
 && adduser --system --group sim

WORKDIR /sim
